version: 0.0
os: linux

files:
  - source: /
    destination: /srv/nextjs
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1200
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: root
