version: 0.2

env:
  variables:
    ARTIFACT_DIR: "/tmp/artifact"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔧 Installing dependencies"
      - apt-get update -y && apt-get install -y jq unzip
      - node -v && npm -v

  pre_build:
    commands:
      - echo "🔑 Fetching SSM parameters (optional)"
      - |
        PARAMS=$(aws ssm get-parameters-by-path \
          --path "$SSM_PREFIX" \
          --with-decryption \
          --region "$REGION" 2>/dev/null || true)
        if [ -n "$PARAMS" ]; then
          echo "Writing .env.production"
          echo "$PARAMS" | jq -r '.Parameters[] | "\(.Name)=\(.Value)"' \
            | sed -E "s|$SSM_PREFIX/([^=]+)=|\1=|" > .env.production
        else
          echo "⚠️  No SSM parameters found, continuing"
        fi

  build:
    commands:
      - echo "📦 Installing dependencies and building Next.js"
      - npm ci
      - npm run build

  post_build:
    commands:
      - echo "📦 Preparing artifact for CodeDeploy"
      - mkdir -p "$ARTIFACT_DIR"

      # Copy app build output
      - cp -r .next "$ARTIFACT_DIR/" || true
      - cp -r public "$ARTIFACT_DIR/" || true
      - cp -r app "$ARTIFACT_DIR/" || true

      # Copy configs & runtime files
      - cp package.json "$ARTIFACT_DIR/" || true
      - cp package-lock.json "$ARTIFACT_DIR/" || true
      - cp next.config.js "$ARTIFACT_DIR/" || true
      - cp -r scripts "$ARTIFACT_DIR/" || true
      - cp -r systemd "$ARTIFACT_DIR/" || true
      - cp appspec.yml "$ARTIFACT_DIR/" || true

      - echo "✅ Artifact prepared"
      - ls -R "$ARTIFACT_DIR"

artifacts:
  base-directory: /tmp/artifact
  files:
    - '**/*'
