version: 0.2

env:
  variables:
    SSM_PREFIX: "/prod/nextjs"          # Change if you use a different prefix
    REGION: "ap-south-1"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔧 Installing dependencies (jq + AWS CLI v2 if missing)"
      - apt-get update -y && apt-get install -y jq unzip
      - |
        if ! command -v aws >/dev/null 2>&1; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip /tmp/awscliv2.zip -d /tmp
          /tmp/aws/install
        fi

  pre_build:
    commands:
      - echo "🔑 Fetching build-time environment variables from SSM"
      - |
        PARAMS=$(aws ssm get-parameters-by-path \
          --path "$SSM_PREFIX" \
          --with-decryption \
          --region "$REGION" 2>/dev/null || true)
        if [ -n "$PARAMS" ]; then
          echo "Writing .env.production from SSM parameters"
          echo "$PARAMS" | jq -r '.Parameters[] | "\(.Name)=\(.Value)"' \
            | sed -E "s|$SSM_PREFIX/([^=]+)=|\1=|" > .env.production
          cat .env.production
        else
          echo "⚠️  No SSM parameters found under $SSM_PREFIX (continuing anyway)"
        fi

  build:
    commands:
      - echo "📦 Installing production dependencies and building Next.js"
      - npm ci
      - npm run build

  post_build:
    commands:
      - echo "📦 Preparing artifact for CodeDeploy"
      - mkdir -p $CODEBUILD_ARTIFACT_PATH
      - cp -r .next package.json package-lock.json public next.config.js scripts systemd appspec.yml $CODEBUILD_ARTIFACT_PATH
      - echo "✅ Build complete. Artifact ready."

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_ARTIFACT_PATH
