version: 0.2

env:
  variables:
    ARTIFACT_DIR: "/tmp/artifact"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔧 Installing system dependencies"
      - apt-get update -y && apt-get install -y jq unzip
  pre_build:
    commands:
      - echo "🔑 Pre-build phase"
      - echo "Checking for .env.production or creating a default one if needed"
      - if [ ! -f .env.production ]; then echo "NEXT_PUBLIC_API_URL=http://example.com" > .env.production; fi
  build:
    commands:
      - echo "📦 Installing dependencies and building Next.js"
      - npm ci
      - npm run build
  post_build:
    commands:
      - echo "📦 Preparing artifact for CodeDeploy"
      - mkdir -p $ARTIFACT_DIR
      - cp -r .next package.json next.config.js public $ARTIFACT_DIR/
      - cp appspec.yml $ARTIFACT_DIR/ || true  # Only if appspec.yml exists
      - echo "✅ Build completed and artifacts prepared"

artifacts:
  base-directory: $ARTIFACT_DIR
  files:
    - '**/*'
