version: 0.2

env:
  variables:
    ARTIFACT_DIR: "/tmp/artifact"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔧 Installing dependencies (jq + AWS CLI v2 if missing)"
      - apt-get update -y && apt-get install -y jq unzip
      - node -v && npm -v

  pre_build:
    commands:
      - echo "🔑 Fetching build-time environment variables from SSM"
      - |
        PARAMS=$(aws ssm get-parameters-by-path \
          --path "$SSM_PREFIX" \
          --with-decryption \
          --region "$REGION" 2>/dev/null || true)
        if [ -n "$PARAMS" ]; then
          echo "Writing .env.production from SSM parameters"
          echo "$PARAMS" | jq -r '.Parameters[] | "\(.Name)=\(.Value)"' \
            | sed -E "s|$SSM_PREFIX/([^=]+)=|\1=|" > .env.production
          cat .env.production
        else
          echo "⚠️  No SSM parameters found under $SSM_PREFIX (continuing anyway)"
        fi

  build:
    commands:
      - echo "📦 Installing production dependencies and building Next.js"
      - npm ci
      - npm run build

  post_build:
    commands:
      - echo "📦 Preparing artifact for CodeDeploy"
      - mkdir -p "$ARTIFACT_DIR"
      # Copy build output and required runtime files
      - if [ -d ".next" ]; then cp -r .next "$ARTIFACT_DIR/"; fi
      - if [ -f "package.json" ]; then cp package.json "$ARTIFACT_DIR/"; fi
      - if [ -f "package-lock.json" ]; then cp package-lock.json "$ARTIFACT_DIR/"; fi
      - if [ -f "next.config.js" ]; then cp next.config.js "$ARTIFACT_DIR/"; fi
      - if [ -d "public" ]; then cp - publicr "$ARTIFACT_DIR/"; fi
      - if [ -d "scripts" ]; then cp -r scripts "$ARTIFACT_DIR/"; fi
      - if [ -d "systemd" ]; then cp -r systemd "$ARTIFACT_DIR/"; fi
      - cp appspec.yml "$ARTIFACT_DIR/" || true
      - echo "✅ Artifact prepared at $ARTIFACT_DIR"
      - ls -l "$ARTIFACT_DIR"

artifacts:
  base-directory: /tmp/artifact
  files:
    - '**/*'
