version: 0.2

env:
  variables:
    ARTIFACT_DIR: "/tmp/artifact"  # ✅ Our own directory path

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔧 Installing dependencies (jq + AWS CLI v2 if missing)"
      - apt-get update -y && apt-get install -y jq unzip
  pre_build:
    commands:
      - echo "🔑 Fetching build-time environment variables from SSM"
      - |
        PARAMS=$(aws ssm get-parameters-by-path \
          --path "$SSM_PREFIX" \
          --with-decryption \
          --region "$REGION" 2>/dev/null || true)
        if [ -n "$PARAMS" ]; then
          echo "Writing .env.production from SSM parameters"
          echo "$PARAMS" | jq -r '.Parameters[] | "\(.Name)=\(.Value)"' \
            | sed -E "s|$SSM_PREFIX/([^=]+)=|\1=|" > .env.production
          cat .env.production
        else
          echo "⚠️  No SSM parameters found under $SSM_PREFIX (continuing anyway)"
        fi
  build:
    commands:
      - echo "📦 Installing production dependencies and building Next.js"
      - npm ci
      - npm run build
  post_build:
    commands:
      - echo "📦 Preparing artifact for CodeDeploy"
      - mkdir -p $ARTIFACT_DIR               # ✅ USE OUR OWN VAR
      - cp -r .next package.json next.config.js public $ARTIFACT_DIR/
      - cp appspec.yml $ARTIFACT_DIR/ || true
      - echo "✅ Artifact prepared at $ARTIFACT_DIR"

artifacts:
  base-directory: /tmp/artifact  # ✅ MUST MATCH ARTIFACT_DIR
  files:
    - '**/*'
